server:
  port: 7901
spring:
  application:
    name: mine-provider-user    # 项目名称尽量用小写(注册到eureka的名字)
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:init.sql          # 指定h2数据库的建表脚本
    data: classpath:insert.sql          # 指定h2数据库的insert脚本
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true     #指定应用微服务在eureka上面的链接为IP地址
    instance-id: ${spring.application.name}:${server.port}