server:
  port: 8050
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaobob/study
          search-paths: config-repo
          username: 844854626@qq.com
          password: ren844854626
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/