server:
  port: 8325
spring:
  application:
    name: springms-provider-user-mysql-hibernate  #全部小写


#####################################################################################################
# mysql 属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///springcloud?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      #ddl-auto: create #ddl-auto:设为create表示每次都重新建表
      ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy #映射字段策略
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#####################################################################################################


#####################################################################################################
# 打印日志
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.springms: DEBUG
#####################################################################################################
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true     #指定应用微服务在eureka上面的链接为IP地址
    instance-id: ${spring.application.name}:${server.port}
